### ISSUE TITLE
Looks like  a typo WebKittransition

### ISSUE THREAD

**Issue by kof** [pburtchaell/react-notification#101]
Looks like  a typo, should be WebkitTransition, no?
https://github.com/pburtchaell/react-notification/blob/master/src/notification.js#L61

**Comment by pburtchaell** [comment]
Yes, that is correct, it should be `WebkitTransition`.

**Comment by pburtchaell** [comment]
Patched in https://github.com/pburtchaell/react-notification/commit/b158752e7d037f3df7f503f572db829039f27af3 and released as `react-notification@6.5.1`.

**Comment by kof** [comment]
thanks.
