### ISSUE TITLE
Multiple line text support

### ISSUE THREAD

**Issue by giuseppeg** [pburtchaell/react-notification#103]
Hi @pburtchaell thanks for this great component :)
Would it be hard to add multiline text support? 

I imagine that we'd need to get a reference to the dom node, grab its height and in turn update all of the tips `bottom` (or top) position. In this case maybe we'd need a new hook like `onActive` that runs at `componentDidMount` time.

I'd be glad to help.

**Comment by pburtchaell** [comment]
Yeah, I think this would be possible. 

Imagining how this could work:
1. Add multiple-line notification to the stack
2. Get height of multi-line notif
2. Store the height as `offSetPosition` (?)
3. Use `offSetPosition` to offset the position of the notif _above_ the multi line notif
4. When notification is removed, reset the value of `offSetPosition` to `0`

So if a multi-line notif has a height of 20px, the notification _above_ would be offset 20px higher than usual. 

If you want to submit a PR for this, please do!

**Comment by VladimirRubin** [comment]
I'm not sure about multi-line text in notifications, because `<span>` tag renders multi-line text in one line.

So i think we have three way to resolve this issue:

1. Add custom HTML messages as notification message (and client can send something like `<p>First Line<p><p>Second Line</p>` as message)
1. Use the `<pre>` tag instead of `<span>` for multi-lene formatting messages
1. Set the custom width to notification block -- so all text will be separated by lines following this block width...

@pburtchaell what do you think about it?

**Comment by giuseppeg** [comment]
@pburtchaell at work I went for a CSS only solution. 

We show notifications on the top right corner, top to down. Instead of positioning each single notification I now position the entire stack container and `onDismiss` is invoked after the *css transition duration milliseconds* with `setTimeout`.

If the position of every notification is `relative` it can still be animated but can also grow in height (have flexible height) and affect the position of the next one.

For the default behavior where notifications are rendered in the bottom left corner from the bottom to up I believe that one could use flexbox as follow

```css
.notification-list {
  position: fixed;
  bottom: 0;
  left: 0;
  display: flex;
  flex-direction: column-reverse;  
}
```

I guess that it'd be nice to make the stack container class `.notification-list` configurable.

**Comment by pburtchaell** [comment]
> at work I went for a CSS only solution

Yeah, @giuseppeg @vladimirRubin a CSS approach (customized with a prop value) would be best because it would allow for variability.

 > I guess that it'd be nice to make the stack container class `.notification-list` configurable.

@giuseppeg, can you create new issue for this since it isn't directly related to this?

**Comment by pburtchaell** [comment]
Marking with the help wanted label and closing because there hasn't been any progress since December. If you'd like to revisit this with a PR, please just reopen the issue.
