### ISSUE TITLE
Notifications from top to the bottom

### ISSUE THREAD

**Issue by valin0k** [pburtchaell/react-notification#104]
Hello, thanks for the great component. Is it possible to make notifications from top to the bottom?
If i add class for className like this:
`
top: 1rem !important;
bottom: auto !important;
right: 1rem;
left: auto !important;`
It works, but all notifications shows at one place

**Comment by pburtchaell** [comment]
You can't change the position styles with CSS. The notification styles are inline and, consequently, will always override CSS properties. If you use the `barStyleFactory` and `activeBarStyleFactory` factory properties, you can customize the styles and position the notification where you would like.  

There is documentation on these properties in the README: https://github.com/pburtchaell/react-notification#barstylefactory-and-activebarstylefactory-notificationstack-props
