### ISSUE TITLE
Update documentation to show correct parameters for onClick function

### ISSUE THREAD

**Issue by BamaBoy** [pburtchaell/react-notification#114]
Hi! The docs [says](https://github.com/pburtchaell/react-notification/blob/7f3d8aefc575f0fbbfb3a5da2726bc4a0654f43b/docs/guides/events.md) that  we can use `deactivate` function to set the notification to inactive. But this feature isn't working :worried:

## Version Number
6.6.0
## Code Example

```
import { NotificationStack } from 'react-notification';
import { OrderedSet } from 'immutable'; // Optional library used for example
import React, { Component } from 'react';

export default class App extends Component {
  constructor () {
    super();
    this.state = {
      notifications: OrderedSet()
    };
  }

  addNotification  = () => {
    const newCount = this.state.notifications.toArray().length + 1;
    return this.setState({
      notifications: this.state.notifications.add({
        message: `Notification ipsum...`,
        key: 'some UID',
        action: 'Dismiss',
        dismissAfter: false,
        onClick: (deactivate) => {
          deactivate();
          this.removeNotification('some UID');
        },
      })
    });
  }

  removeNotification = (count) => {
    this.setState({
      notifications: this.state.notifications.filter(n => n.key !== count)
    })
  }

  render () {
    return (
      <div>
         <button onClick={this.addNotification}>add</button>
      <NotificationStack
        notifications={this.state.notifications.toArray()}
        onDismiss={notification => this.setState({
          notifications: this.state.notifications.delete(notification)
        })}
      />
      </div>   
    );
  }
}
```

## Expected behavior
When click on `dismiss` notification becomes inactive
## Actual Behavior
Got error `deactivate is not a function`

**Comment by pburtchaell** [comment]
Sorry for the delay! I've been swamped this week. I'm going to try to take a look at this next week. In the meantime, would you mind [looking at the test](https://github.com/pburtchaell/react-notification/blob/master/test/notificationStack.js#L15) for this feature and making a PR that demonstrates the bug? If you can, that would be immensely helpful.

Alternatively, @joeyfigaro or @BerkeleyTrue might be able to take a look.

**Comment by joeyfigaro** [comment]
@pburtchaell @BamaBoy I'll see about taking a look at this later today.

**Comment by BamaBoy** [comment]
@pburtchaell @pburtchaell Thanks for answers! Sorry for delay :( 
Actually it's not a bug. `onClick` function get's two arguments: notification and `deactivate` function. 
It wasn't obvious for me, that `deactivate` function is a second argument.
You can close this.

Thanks for your answers again!!!

**Comment by pburtchaell** [comment]
@BamaBoy gotcha! That's our mistake then. It looks like [the documentation](https://github.com/pburtchaell/react-notification/blob/master/docs/introduction.md) doesn't correctly list the parameters of the `onClick` function.

I'm reopening this issue until one of us can make a quick update to the docs. 👍

**Comment by pburtchaell** [comment]
Resolved in https://github.com/pburtchaell/react-notification/commit/2beea2e983d633f909a8d0d7759a773116a6c1da
