### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by qoalu** [pburtchaell/react-notification#115]
## Version Number
6.6.0
## Steps to Reproduce
git clone ***
npm install

## Expected Behavior
installs
## Actual Behavior
```
> `npm bin`/eslint src/**/*.js test/**/*.js
'`npm' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by pburtchaell** [comment]
What is your operating system?

**Comment by pburtchaell** [comment]
This looks like it is because you do not have npm installed. If you Google the error, there will be plenty of guides to help you: https://www.google.com/#q='`npm'+is+not+recognized+as+an+internal+or+external+command,+operable+program+or+batch+file.

**Comment by qoalu** [comment]
I am on Windows, thanks, I will see if I can still run it

**Comment by corydeppen** [comment]
Just to relate this to the PR that resolved the issue of `` `npm bin` `` not running on Windows, see #129.
