### ISSUE TITLE
Notification bar style

### ISSUE THREAD

**Issue by EmmaHansson** [pburtchaell/react-notification#117]
Unfortunately, I don't know how to normally override one style element.
The component uses left: 1rem by default. But it causes to issue when you have left pane for example in bootstrap.

How to change this style to left: auto ?

**Comment by pburtchaell** [comment]
Assuming you are using the `NotificationStack` component, [there are props for custom styles](https://github.com/pburtchaell/react-notification/blob/master/docs/guides/styles.md#barstylefactory-and-activebarstylefactory-notificationstack-props) to reposition each notification. 

You can also just these the `style` prop as you would normally.


```jsx
<NotificationStack
  notifications={[...]}
  style={{
    // custom style for notification
  }}
  activeBarStyleFactory={(index, defaultStyles) => Object.assign(
    defaultStyles,
    { 
      // some custom styles to apply to each notification
      bottom: `${index + 2}px` 
    }
  )}
/>
```

**Comment by EmmaHansson** [comment]
It's not so simple then.
Let's assume a scenario when I popup messages in following order. If message count even then the style should be red, and when it's odd then style should be green. Background colors I mean.

So using, setState() I may change styles I guess. OK. But in this case all bars will be the same color changing all after each popup. How to resolve this happy case ? :)

**Comment by pburtchaell** [comment]
> If message count even then the style should be red, and when it's odd then style should be green.

The function for `activeBarStyleFactory` does provide the `index` parameter, which is an integer unique to each notification. For example, if you have two notifications, the indexes would be `0` and `1`. That _could_ solve your issue, but I think you'd probably still run into issues.

A better solution would be to provide the notification to you:

```jsx
<NotificationStack
  notifications={[...]}
  style={{
    // custom style for notification stack
  }}
  activeBarStyleFactory={(index, notification, defaultStyles) => Object.assign(
    defaultStyles,
    { 
      // some custom styles to apply to each notification
      bottom: `${index + 2}px` 
    }
  )}
/>
```
I'm not available right now to implement that feature, but if you'd like, you could make a PR. 

@joeyfigaro or @BerkeleyTrue would you be interested in taking a stab at this?

**Comment by pburtchaell** [comment]
Thanks to a PR from @BamaBoy, this has been implemented in version `6.7.0`. 💯

**Comment by EmmaHansson** [comment]
Please update manual/wiki also for this param.

**Comment by pburtchaell** [comment]
[It has already been updated](https://github.com/pburtchaell/react-notification/blob/master/docs/guides/styles.md#barstylefactory-and-activebarstylefactory-notificationstack-props).
