### ISSUE TITLE
Version 6.6.2 missing on NPM

### ISSUE THREAD

**Issue by noxan** [pburtchaell/react-notification#120]
Version `6.6.2` does not exist on NPM.

While version `6.6.1` shows the following message:
```warning react-notification@6.6.1: An extraneous dependency was erroneously added to 6.6.1. Please update to 6.6.2 to remove this dependency.```

**Comment by pburtchaell** [comment]
Fixed!

**Comment by noxan** [comment]
Wow, what an absolutely impressive reaction time. Thanks for the effort, keep it up! 👍
