### ISSUE TITLE
Show up on the right side

### ISSUE THREAD

**Issue by tomgutz** [pburtchaell/react-notification#125]
Hi, any chance the notificaiton show up on the right-bottom side of the screen. I saw the code for stacked notification and it seems the style for left absolute position is directly injected or inline styled.

**Comment by BamaBoy** [comment]
@tomgutz Yep. You can add `barStyleFactory`, `activeBarStyleFactory` to `NotificationStack` component. 
Here's some code example: 

```
function barStyleFactory(index, style) {
  return Object.assign(
    {},
    style,
    { bottom: `${2 + (index * 4)}rem`, left: 'auto', right: '-100%' }
  );
}

function activeBarStyleFactory(index, style) {
  return Object.assign(
    {},
    style,
    { bottom: `${2 + (index * 4)}rem`, left: 'auto', right: '1rem' }
  );
}

<NotificationStack
  notifications={this.state.notifications}
  barStyleFactory={barStyleFactory}
  activeBarStyleFactory={activeBarStyleFactory}
/>
```

**Comment by tomgutz** [comment]
Yeah I kinda noticed it. And I was at the moment experimenting for the right combination to make it work. Thanks! Appreciate the tip!
