### ISSUE TITLE
Prevent ESLint errors when building on Windows

### ISSUE THREAD

**Issue by corydeppen** [pburtchaell/react-notification#127]
While working on a PR and building the source, I received over 1,000 `linebreak-style` ESLint errors due to being on a Windows machine that checked out files using CRLF linebreaks. I've seen numerous GitHub [conversations](https://github.com/airbnb/javascript/pull/1224) about this across various projects, including the note on the [docs page for the ESLint rule](http://eslint.org/docs/rules/linebreak-style#using-this-rule-with-version-control-systems). It seems like a common way to enforce LF linebreaks and prevent linting errors for devs working on Windows is to add a `.gitattributes` file with `* text=auto` and disable the `linebreak-style` rule.

> When text is set to "auto", the path is marked for automatic end-of-line conversion. If Git decides that the content is text, its line endings are converted to LF on checkin. When the file has been committed with CRLF, no conversion is done. ([source](https://git-scm.com/docs/gitattributes#gitattributes-Settostringvalueauto))

**Comment by pburtchaell** [comment]
Yes, let's fix this. Does #127 resolve this for you?

**Comment by corydeppen** [comment]
Yes, #128 clears up those errors.

However, one last Windows hurdle (sorry)...

Windows chokes on the `"./bin/test.sh"` path in the `test` script and only works if I changes to backslashes. Using [cross-env](https://github.com/kentcdodds/cross-env) handles the existing path as expected on Windows, though.

`"test": "cross-env ./bin/test.sh"`

Would you be open to giving that a go?
