### ISSUE TITLE
Add hosted examples

### ISSUE THREAD

**Issue by SilencerWeb** [pburtchaell/react-notification#148]
It would be cool if u deploy ur examples at least on github pages because it is much easier to open a link and see all examples instead of cloning repo, installing dependencies and finally see examples

**Comment by pburtchaell** [comment]
I agree this would be nice. It does take a bit more work than you would expect though.

I'm currently working on #143, which updates the build tool for the examples. I'm going to mark this as a good first issue. It would be nice for someone else to take this on.
