### ISSUE TITLE
NotificationStack.propTypes.action should accept a node.

### ISSUE THREAD

**Issue by BerkeleyTrue** [pburtchaell/react-notification#152]
When using NotificationStack to supply a action element that is something other than a string (in our case we are supplying a react element) React logs a proptype warning. 

StackedNotification and Notification all use the defaultPropsTypes.action which gives you the option of using a Node.

easy fix would just to change the propType for action to use the defaultPropTypes property for the same value.

```js
NotificationStack.propTypes = {
  activeBarStyleFactory: PropTypes.func,
  barStyleFactory: PropTypes.func,
  actionStyleFactory: PropTypes.func,
  dismissInOrder: PropTypes.bool,
  notifications: PropTypes.array.isRequired,
  onDismiss: PropTypes.func.isRequired,
  onClick: PropTypes.func,
  action: defaultPropTypes.action
};
```

Can put together a PR.

**Comment by pburtchaell** [comment]
Makes sense! Feel free to do this.
