### ISSUE TITLE
Multiple notifications at the same time

### ISSUE THREAD

**Issue by pengux** [pburtchaell/react-notification#17]
Is it possible to show multiple notifications at the same time? I've check the source, but didn't see a way to do it.

**Comment by pburtchaell** [comment]
It is certainly possible if you give each notification a different `ref`. The trouble you would probably run into is styling the notification appropriately so that the notifications stack on top of each other.

**Comment by pburtchaell** [comment]
Just a note that I am working on this in the version 2.0.0 release if you want to take a look. There is an example with multiple styles.

**Comment by pengux** [comment]
Looking forward to it :+1:

**Comment by pburtchaell** [comment]
Alright, just pushed up [the example](https://github.com/pburtchaell/react-notification/blob/master/examples/es2015/index.js). Let me know if you think it would work for what you are doing.

The notification component has no state nor any knowledge of other notifications; it is up to you how you control the position of multiple notifications. I am, however, not opposed to adding logic to the notification that handles this.

If I did, what I would imagine is that there would be a `order` prop (or something similar) that tells each component how many other notifications there are and controls what order the notifications should be in. Based off this prop, the component could change it's position. 

For example, if a notification component has an `order` of `1`, it would be positioned at the bottom. If you add a second notification, you increase `order` of the first notification to `2`. This tells the notification it is the _first_  out of _two notifications total_; its position is changed to make room for the new notification. Now, the second notification would have an `order` of `1` and be positioned at the bottom.

If this is the route we go, I could imagine two things:

1. Controls the value of `order` yourself
2. Make a second component (`<NotificationList />`?) that controls the order of notifications?

I'd prefer option 1.

**Comment by pengux** [comment]
Well, if option 1, then you need to keep another state in your application and sets/unsets it correctly when your notification change. I rather have the component do all this for me and just pass in an array of notifications to have them displayed in the order they are in the array. It's more convenient...
