### ISSUE TITLE
dismissAfter is not working

### ISSUE THREAD

**Issue by halhelms** [pburtchaell/react-notification#19]
Everything else seems to be working fine but in both Safari and Chrome, the dismissAfter doesn't hide the notification. Is this a known issue?

**Comment by web2style** [comment]
I'm experiencing the same issue. Any ideas?

**Comment by tran2** [comment]
The code doesn't actually use the dismissAfter value to hide the notification. I've created a pull request to fix that. For now you might want to do your own timer and call Notification.hide on your own.

**Comment by pburtchaell** [comment]
Hey guys, sorry for the delay on this. It has been a busy week. I'm going to look into it this weekend. A couple of weeks I started rewriting the component in ES6 so I make sure the prop is properly working when I release it.

**Comment by pburtchaell** [comment]
Just a note that I am working on this in the version 2.0.0 release if you want to take a look.

**Comment by pburtchaell** [comment]
Closing as this is resolved by #20. If you still have issues, please reopen.
