### ISSUE TITLE
dismissAfter not working

### ISSUE THREAD

**Issue by That-David-Guy** [pburtchaell/react-notification#29]
Hi, nice component!

I'm having some trouble with the dismissAfter. I followed your guidelines and have the following in my render component.

````
<Notification
          isActive={true}
          message={'Saved! (Speech will also save automatically every few seconds)'}
          action={''}
          onClick={this._onNotificationClick}
          onDismiss={this._onNotificationDismiss}
          style={{ bar: { bottom: '6rem', fontSize: '1.5rem', zIndex: '1'}}}
          dismissAfter={2000}
        />
````

But it doesn't dismiss after 2 seconds. Is there something I'm missing?

**Comment by pburtchaell** [comment]
What does your `_onNotificationDismiss` function look like?

**Comment by That-David-Guy** [comment]
```
  _onNotificationClick: function(e) {
    console.log('onClick', e);
  },

  _onDismiss: function(e) {
    console.log('onDismiss', e);
  },

```
I'll try using the `this.state.isActive`

**Comment by That-David-Guy** [comment]
```

**Comment by pburtchaell** [comment]
I think you need to check your function names. The onDismiss prop calls the function `this._onNotificationDismiss`, which does not exist.

**Comment by pburtchaell** [comment]
I'm closing this issue as it is not an issue with the source of this component.

**Comment by That-David-Guy** [comment]
Damn, that's embarrassing.

Works like a charm now, thanks!

**Comment by pburtchaell** [comment]
No worries! It happens. :smile:
