### ISSUE TITLE
Error on require('react-notification')

### ISSUE THREAD

**Issue by RacingTadpole** [pburtchaell/react-notification#4]
When I add

    var Notification = require('react-notification');

to the top of my jsx component (even with no `<Notification>` tags yet), I get the error:

```
.../node_modules/react-notification/index.js:57
      <div className={classes}>
      ^
ParseError: Unexpected token
    at wrapWithPluginError (.../node_modules/gulp-browserify/index.js:44:10)
...
```

Have you seen this?  I'm using React 0.12.2.  Thanks!

(PS. Did you mean for your class names to be missing one of the 'i's in notification?)

**Comment by pburtchaell** [comment]
Fixed in the latest release.
