### ISSUE TITLE
Overlapping NotificationStack

### ISSUE THREAD

**Issue by markortiz** [pburtchaell/react-notification#47]
`NotificationStack` is overlapping over each other instead of adding it at the top of the previous stack.

**Comment by pburtchaell** [comment]
I'm happy to figure out what is going on, but can you provide some more context please? A screenshot or gif of the issue as well as an example of your code would be useful. Could you also inspect the DOM and send me examples of the DOM Node tree for the component?

**Comment by markortiz** [comment]
I just clone your master and run `npm start` and this is what I got.

![animation](https://cloud.githubusercontent.com/assets/1829168/13239494/b998df24-da15-11e5-9f0b-e7ea53e3b739.gif)

**Comment by pfraze** [comment]
I'm experiencing this as well

**Comment by pfraze** [comment]
https://github.com/pburtchaell/react-notification/blob/master/src/notificationStack.js#L27

That's the issue, it should be merging those styles instead of choosing between them

**Comment by pburtchaell** [comment]
Great. I am not available presently, but when I have some time this week I'm going to review the code and make sure this issue is resolved. :smile:

**Comment by uro5h** [comment]
Quick fix would be to provide style object to notification.add():

`this.state = {
            notifications: OrderedSet()
}

...

return this.setState({
            notifications: notifications.add({
message: 'some message',
key: someKey,
style: {
                        bar: {
                            bottom: (2 + notificationCount * 4) + 'rem' // tweak as you like
                        }
                    }
}`

**Comment by chmac** [comment]
@pburtchaell Any updates? Looks like we're hitting the same issue...

**Comment by pburtchaell** [comment]
This should be fixed in `react-notification@5.0.0`. Keep in mind the [breaking changes](https://github.com/pburtchaell/react-notification/releases/tag/5.0.0), which are documented in the release as well as the README.

**Comment by pfraze** [comment]
Thanks!
