### ISSUE TITLE
NotificationStack requires onDismiss

### ISSUE THREAD

**Issue by chmac** [pburtchaell/react-notification#50]
I think the issue is [here](https://github.com/pburtchaell/react-notification/blob/master/src/notificationStack.js#L24). The `onDismiss` function doesn't check to see if `this.props.onDismiss` exists or not.

**Comment by pburtchaell** [comment]
Yes, the NotificationStack requires an `onDismiss` function in order to remove notifications from the stack when the timer runs out. This is a required property. [See the example](https://github.com/pburtchaell/react-notification/blob/master/examples/notification-tree/index.js).
