### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by i-do-not-know-how-to-code** [pburtchaell/react-notification#55]
Hello, yes. I would like for you to please tell me how to write an application to use this. Your README does not tell me how.

Thanks you for your help, I am most grateful.

**Comment by i-do-not-know-how-to-code** [comment]
Hello, yes. I do not understand why this closed. I would like help. If this is wrong place, please tell me where to find the help I am in need of.  

Thanks you muchly kind sir, I am most grateful.

**Comment by pburtchaell** [comment]
I closed this issue because your request is outside the scope of the project and it is not my responsibly to explain to you how to code. If you need assistance I would recommend a different source such as StackExchange or [the React community on Discord](http://www.reactiflux.com).
