### ISSUE TITLE
Override value of "bottom" CSS attribute

### ISSUE THREAD

**Issue by brianespinosa** [pburtchaell/react-notification#57]
I looked through the code for this component and it appears that the `bottom` CSS attribute is hard coded in this component with the logic for placement passed on to each notifications. Are you opposed to a solution that would allow the `barStyle` property to also set `bottom` in a dynamic way?

**Comment by pburtchaell** [comment]
Part of the problem is the dynamic position is determined using a numeric value and then the unit is concatenated with the numeric value, e.g., `barPositon + 'rem'`. I am not opposed to add this, but I think there would need to be two new props introduced: `bottomPositionUnit` and `bottomPosition`.

**Comment by brianespinosa** [comment]
Yeah, that was what I was thinking. It would need to be a prop specific to NotificationStack. I mainly wanted to confirm you were okay with this before I did the work and submitted a PR. I will update the README documentation for NotificationStack also to reflect that barStyle and others can now be passed to children from your last update.

**Comment by pburtchaell** [comment]
Awesome! I'll keep an eye out for the PR. :smile:

**Comment by pburtchaell** [comment]
Another possible approach to this: make `barStyle` a function and the argument can be the index of the notification. 

```js

// if this is the 2nd notification in the stack, index will have a value of 2
barStyle={index => ({
  ...,
  bottom: `${index*3}rem` // do some math to get the right position
})}
```

**Comment by RamonBeast** [comment]
I found this issue while looking for a solution and that's a good idea, at least placement of the notifications can be more flexible.

**Comment by pburtchaell** [comment]
@brianespinosa, any interest in making a PR for this?
