### ISSUE TITLE
Uncaught TypeError: Object.assign is not a function

### ISSUE THREAD

**Issue by samcorcos** [pburtchaell/react-notification#65]
I feel like I must be missing something obvious here. I'm getting the error:

`Uncaught TypeError: Object.assign is not a function`

The error is caused by the `isActive` ternary:

```js
return isActive ? Object.assign({}, baseStyle, {
        left: '1rem'
      }, barStyle, activeBarStyle) : Object.assign({}, baseStyle, barStyle);
```

Do I need to add a polyfill in order to get this package to work?

I'm using webpack and babel for compilation. If you want to see my config, I can add it.

**Comment by pburtchaell** [comment]
`Object.assign` should be covered by the babel polyfill. Is it include in your project?

**Comment by samcorcos** [comment]
Yeah, I wasn't using polyfill in my entry point. I changed it to the following and everything worked.

```js
  entry: [
    'webpack-dev-server/client?http://localhost:3000',
    'babel-polyfill',
    './app/index'
  ],
```

Might be worth noting in the docs that the polyfill is necessary, but it sounds like everyone else already knew how to solve this. Thanks for putting this together! Saved me a lot of time.
