### ISSUE TITLE
onDismiss broken in 5.0.3

### ISSUE THREAD

**Issue by pdeva** [pburtchaell/react-notification#66]
It seems #61 broke the `onDismiss` behavior completely.
The event doesnt fire at all now.

The last working version is 5.0.1

**Comment by pburtchaell** [comment]
Thanks for reporting this. @elrumordelaluz do you have any insight on the issue?

I don't have time to review the code this week, but if either of you see the issue and can make a PR I would appreciate it. Otherwise, I will get to it as soon as I can next week.

**Comment by elrumordelaluz** [comment]
@pburtchaell I'm sorry, my fault. [this](https://github.com/elrumordelaluz/react-notification/commit/34d5d31a48fb5b58805d693c2e00f9a32e3f7c28) should work. 

Please let me know what do you think about _detect_ between Stacked Notification and Normal Notification using `isLast`.

**Comment by pburtchaell** [comment]
I think this should work @elrumordelaluz. If you have time, can you also add a unit test to cover this issue?

**Comment by elrumordelaluz** [comment]
Sure @pburtchaell . 

Will try to put something this week.

**Comment by gpietro** [comment]
Still not working on version 5.0.4 # #68 # @pburtchaell

**Comment by elrumordelaluz** [comment]
@gpietro could you show what behaviour you get? 

![react-notif-simple](https://cloud.githubusercontent.com/assets/784056/15247299/a187e5e6-1913-11e6-9cff-4d7d4d4f4359.gif)

All seems ok for me: `onDismiss` fires on:
- clicking _show/hide_ button
- automatically after `dismissAfter` timeout
- clicking _dismiss_ notification button

**Comment by gpietro** [comment]
I'm wrapping the component but the onDismiss is never reached (dismissAfter set at 2000 as default). Only works on version 5.0.2.
[My wrapper code](https://gist.github.com/gpietro/3fd2f5891882f62e89b3873e35530f37)

**Comment by elrumordelaluz** [comment]
@gpietro did you tried binding `onDismissNotification` in the `constructor()` like:

```js
this.onDismissNotification = this.onDismissNotification.bind(this);
```

or calling it like `onDismiss={this.onDismissNotification.bind(this)}` ?

I think in your actual code shouldn't work `onClick`, right?

**Comment by pburtchaell** [comment]
@gpietro You could also directly fire `onDismiss={NotificationActions.notification.dismiss}`. It's not really necessary to wrap it in another function.
