### ISSUE TITLE
NotificationStack.onDismiss is required?

### ISSUE THREAD

**Issue by radicaled** [pburtchaell/react-notification#71]
https://github.com/pburtchaell/react-notification/blob/87b2f0b24b396f68c18bf4a4cda054af9a76b9cd/src/notificationStack.js#L24

```javascript
onDismiss={props.onDismiss.bind(this, notification)}
```

If `onDismiss` isn't present, we get an undefined method error. However, the proptypes don't require this:

```javascript
NotificationStack.propTypes = {
  notifications: PropTypes.array.isRequired,
  onDismiss: PropTypes.func
};
```

Not sure if bug in `propTypes` or bug in how `onDismiss` is used.

**Comment by pburtchaell** [comment]
Yes, `onDismiss` is required. This is patched in `react-notification@5.0.6`. 😄
