### ISSUE TITLE
Pass HTML as message

### ISSUE THREAD

**Issue by JasonEtco** [pburtchaell/react-notification#73]
Hey! I love this package, it's wonderful. However, right now I'm trying to pass some HTML markup as the message, but as far as I understand I can only pass it as a string or a React component.

Am I doing something wrong, or will you be adding this feature if it doesn't already exist?

Thanks!

**Comment by pburtchaell** [comment]
@JasonEtco Can you clarify what you mean by HTML markup? [The prop accepts elements](https://github.com/pburtchaell/react-notification/blob/master/src/defaultPropTypes.js#L4-L7).

**Comment by JasonEtco** [comment]
@pburtchaell sure;

I've been able to use:
```
function el() {
  return <p><strong>FIRE</strong>You dropped that task like it was hot.</p>;
}
```
And then passing that as the message. However, I'm fairly certain there's a smarter way of doing this. Any chance you could help me out?

By the way, I've refashioned the adding/removing notification functions into Redux actions/reducers, and I'm passing the message differently for every different action.

**Comment by pburtchaell** [comment]
I'll need a bit more context. @JasonEtco. Can you provide me with the code the notification component is wrapped in?

**Comment by JasonEtco** [comment]
@pburtchaell I'm not sure any more code would help you; I'm giving it the `message` prop in a normal way. I think my confusion is in creating a React element. I may have figured it out though, by using `React.createElement` (which is a little bulky, but hey it works).

**Comment by pburtchaell** [comment]
Yep, that method works. Let me know if you have any other issues.
