### ISSUE TITLE
examples not found

### ISSUE THREAD

**Issue by cristian-sima** [pburtchaell/react-notification#76]
On [this page](https://www.npmjs.com/package/react-notification), click 

![image](https://cloud.githubusercontent.com/assets/12199042/16583831/c83f4e32-42c0-11e6-8045-d916e199e10e.png)

results in 404

**Comment by pburtchaell** [comment]
The link should be directing you to [this page](https://github.com/pburtchaell/react-notification/tree/master/examples), but it appears to be broken.

**Comment by pburtchaell** [comment]
Resolved: https://github.com/pburtchaell/react-notification/commit/395d007b9c9dc68d69bcba566004260f2faf7c38
