### ISSUE TITLE
Remove all inline styles

### ISSUE THREAD

**Issue by cristian-sima** [pburtchaell/react-notification#77]
Hi.

I want to use [these classes ](http://v4-alpha.getbootstrap.com/components/alerts/), but when I add them nothing is changing.

If I set `style` to false, the animation is no longer working

**Comment by cristian-sima** [comment]
@pburtchaell any idea here?

**Comment by pburtchaell** [comment]
@cristian-sima The class names should be added to the component, but if the style is not changing, then this is a bug. I'll try to find time to patch the code and add a unit test.

**Comment by pburtchaell** [comment]
I added unit tests for this: https://github.com/pburtchaell/react-notification/commit/7fc6b6264d8d5317bf49fcfa6df63f3cc905f2c7. The tests pass, which means this is not a bug and class names are added to the component. 

1. Can you confirm which version of the middleware you are using? 
2. Did you confirm the class name is not added? 

Please keep in mind this is not an override: the styles from the component will still be included. I think what you want is no inline styles — only animation, right?

**Comment by cristian-sima** [comment]
Yes. I do not want the inline style, but I want to save the position and the animations (as I set `inlineStyle` to `false` it is disabled)

**Comment by pburtchaell** [comment]
@cristian-sima, you can't do this with the current version of the component. However, PR #78 should provide you with a method for this.

**Comment by cristian-sima** [comment]
Thank you

**Comment by cristian-sima** [comment]
@pburtchaell Can you provide an example which works? Cause I have tried using Bootstrap and it does not work

**Comment by cristian-sima** [comment]
It seems that the styles are no longer there, but neither the position and dimensions
