### ISSUE TITLE
Clicking on non-action area should dismiss notification

### ISSUE THREAD

**Issue by BerkeleyTrue** [pburtchaell/react-notification#79]
Totally down to create a PR.

**Comment by pburtchaell** [comment]
Could you explain further, @BerkeleyTrue? A use case for this request would also be appreciated. 😄 Thanks!

**Comment by BerkeleyTrue** [comment]
Some of our notifications are longed lived. It would be nice to give the user the option to dismiss a notification simply by interacting with it.

According to Google Material docs, this is usually done with a swiping action, but I think just a simple click is sufficient.

**Comment by BerkeleyTrue** [comment]
@pburtchaell What do you think? Can I start putting something together. We are looking to get these features into production as soon as possible.

**Comment by benjasHu** [comment]
Any news of this implementation? @BerkeleyTrue
