### ISSUE TITLE
Dismiss notification changes

### ISSUE THREAD

**Issue by BerkeleyTrue** [pburtchaell/react-notification#80]
**Proposed changes**
- _Click on action area to dismiss_: When clicking on an action, for instance a submit action, this should also remove the active status of the notification and initiate dismiss. 
-  _Click on non-action area to dismiss_ (originally #79): Dismiss when clicking anywhere on the notification, but the action. 

From issue #79: 

> Some of our notifications are longed lived. It would be nice to give the user the option to dismiss a notification simply by interacting with it. According to Google Material docs, this is usually done with a swiping action, but I think just a simple click is sufficient.

**Comment by pburtchaell** [comment]
I'm closing this since it seems related to #79. Please reopen if this is a misunderstanding.

**Comment by BerkeleyTrue** [comment]
This would be separate to #79.

When clicking on an action, for instance a submit action, this should also remove the active status of the notification and initiate dismiss. 

#79 would dismiss on clicking anywhere on the notification but the action. This issue would be to optionally dismiss a notification if the action is clicked.

**Comment by BerkeleyTrue** [comment]
@pburtchaell What are your thoughts here? This is something we would require to keep moving with this project.

**Comment by pburtchaell** [comment]
@BerkeleyTrue I'll back to you tomorrow. I apologize for the delays here. I have been swamped at work lately.

**Comment by pburtchaell** [comment]
In order to consolidate #79 and #80, I am going to merge the two issues. I also updated this issue with a description. This will help me understand the feature requests and how they relate. **My understanding of your feature requests — dismiss on action area and dismiss on non-action area — is they are mutually exclusive.** Is this correct? If so, can you explain which would be default and what the new props would be? If I am misunderstanding, can you clarify?

**Comment by BerkeleyTrue** [comment]
The updated description looks great. 

> can you explain which would be default and what the new props would be?

My understanding of the material docs is that the default would be to have both of these options enabled. But I don't know if that is a good default for a library. Instead these should both be optionally enabled

I propose we change onClick to OnAction, add dismissOnAction dismissOnClick booleans

```js
interface props {
  onAction: () => Any, // function to call when action area is clicked
  onDismiss: () => Any, // function to call when notification is dismissed
  dismissOnAction: Boolean, // call onDismiss if action area is clicked after calling onAction
  dismissOnClick: Boolean // call onDismiss if non-action area is clicked
}
```

**Comment by BerkeleyTrue** [comment]
Another option is to change onClick's behavior
```js
interface props {
  // function to call when non-action area is clicked,
  // user can specify the same function as onDismiss
  onClick: () => Any,
  onAction: () => Any, // function to call when action area is clicked
  onDismiss: () => Any, // function to call when notification is dismissed
  callDismissOnAction: Boolean, // call onDismiss if action area is clicked after calling onAction
}
```

**Comment by BerkeleyTrue** [comment]
@pburtchaell Which option do you like?

**Comment by pburtchaell** [comment]
I can't imagine a use case for `onClick`, so I'd go with the first proposal.

**Comment by idpocky** [comment]
For adding a click event to the notification item(the whole wrapper), I added an `<a />`tag into the message, just like this:
```javascript
const n = props.notification; // Create the notification by props.
...// Set other params...
if (notification.onClick && typeof notification.onClick === 'function') {
  n.onClick = (deactivate) => {
    deactivate();
    setTimeout(() => props.notification.onClick(), 400);
  }
}
if (n.onItemClick && typeof n.onItemClick === 'function') {
  n.message = (
    <span>
      <span>{n.message}</span>
      <a
        className="notification-item-click"
        href=""
        style="position: absolute; left: 0; right: 1rem; top: 0; bottom: 0;"
        onClick={
          (event) => {
            event.preventDefault();
            // Run click event to dismiss the notification while clicking the item.
            props.notification.onClick(); 
            n.onItemClick();
          }
         }
      >&nbsp;</a>
    </span>
  );
}
```
The rendered html is:
```html
<span class="notification-bar-message">
    <span>
        <span>The notification need to be Clicked...</span>
        <a class="notification-item-click" href="">&nbsp;</a>
    </span>
</span>
```
It worked. But the animation of dismiss will lose while clicking the item. So I think add a definition of itemClick with the deactivate func is a good idea.

**Comment by yoonwaiyan** [comment]
Any updates on this issue? I've seen both onClick and onDismiss but seems like onClick couldn't do much except deactivating the notification. I need a backend call to set my notification to "read" so that the same notification will not be displayed anymore but currently I can only do that in onDismiss, any way I can use onClick to get at least the "key" of the notification so that I can pass in to backend?

**Comment by pburtchaell** [comment]
Marking with the help wanted label and closing because there hasn't been any progress since last July. If you'd like to revisit this with a PR, please just reopen the issue.
