### ISSUE TITLE
Programmatically dismiss notifications in notifcations stack

### ISSUE THREAD

**Issue by tvedtorama** [pburtchaell/react-notification#82]
Hi,

I have a notification stack, where I first removed items on my onClick() handler.  This works, but the notifications disappears without the nice animation. (The animation works when items are dismissed on timeout.)

I then switched to keeping all the notifications in the list, but instead toggling isActive on the item in the data structure passed to the stack.  Nothing happens.

What would be the correct way to "programmatically" dismiss an item in the notification stack, so that the animation is preserved?

**Comment by pburtchaell** [comment]
Sorry for the delayed response. I will get back to you this week.

**Comment by pburtchaell** [comment]
@tvedtorama The short answer is right now you can't. I will mark this as a requested feature. I don't have the time now to implement it, but if you are available and interested in implementing it, please feel free!

**Comment by tvedtorama** [comment]
@pburtchaell Thank you for the feed back!  I might be able to look into this, but not right now.  For my current needs your library works perfectly.

**Comment by pburtchaell** [comment]
This is released as `react-notification@6.3.0`. See [release notes](https://github.com/pburtchaell/react-notification/releases/tag/6.3.0). Thank you, @ecfairle!

**Comment by iBasit** [comment]
still buggy
