### ISSUE TITLE
Multiple stacks with different positions

### ISSUE THREAD

**Issue by hakunin** [pburtchaell/react-notification#83]
Hi,
I like how minimalistic yet functional this is.

One thing I am missing is being able to have mulitple stacks in different positions.

Although I can see how bottom left is the right way to do it for today's apps, migrating an app that has multiple/different positioned stacks into `react-notification` means to get the team involved even if all you want to do is to use a different library.

Update: I just realised I need sticky notifications as well so as much as I like the minimalistic approach, its a bit too minimal for me right now.

**Comment by BerkeleyTrue** [comment]
@hakunin Because of the way react-notifications let's you manage the notifications queue, you can easily create your own separate stacks and use two instances of NotificationStack component, one for each side. Then just change the css for the opposite side stack using the (active)barStyle prop.

**Comment by pburtchaell** [comment]
@hakunin Does this resolve your issue?

**Comment by hakunin** [comment]
Its more of a suggestion. I went with the other package for notification as I don't have to hack it to make it work like I need.
