### ISSUE TITLE
Trigger add notification function programmatically

### ISSUE THREAD

**Issue by marcuskyril** [pburtchaell/react-notification#84]
Hello. 

I'm working on a dashboard that receives notification data at 10 second intervals. I was wondering if there's a way to add a new notification whenever I receive this data? 

Thanks!

**Comment by BerkeleyTrue** [comment]
Hello @marcuskyril,

React-notification does not directly control the notification queue. You should be able to add notifications to the stack by adding them to the notifications array passed to NotificationStack component.

**Comment by marcuskyril** [comment]
Thanks @BerkeleyTrue! I'm kinda new to this React thingy. How do I achieve this?

**Comment by pburtchaell** [comment]
@marcuskyril, you will need to wrap the notification component in another component and maintain an array of notifications in the state. You can [check the examples](https://github.com/pburtchaell/react-notification/tree/master/examples), which use an immutable data library. Note: immutable is not necessary for all cases; you can use the component without it.
