### ISSUE TITLE
babel-preset-es2015 does not polyfill Object.assign

### ISSUE THREAD

**Issue by pouu69** [pburtchaell/react-notification#85]
IE11

Object.assign error cause

why?

**Comment by BerkeleyTrue** [comment]
@pouu69 Please be more descriptive of the issue. 

Can you provide steps to reproduce?
A stack trace?

**Comment by pouu69** [comment]
sorry im korean i can speak english a little

anyway 

error message : Object doesn't support property or method 'assign'  dist/stackedNotification.js 65 line

**Comment by BerkeleyTrue** [comment]
Hey @pouu69 
How about steps to reproduce?

**Comment by pouu69** [comment]
sorry i can't explain.
it is very complex

i think Object.assign is not supported in IE

so you must rebuild with 'babel-plugin-transform-object-assign' plugin

**Comment by BerkeleyTrue** [comment]
@pouu69 Object assign is already polyfilled by babel using es2015 preset. You can verify that by looking at the dist file yourself.

**Comment by pouu69** [comment]
really ? but dist/~~.js  use Object.assign method

hmm i don;t know why

**Comment by pburtchaell** [comment]
Closing because the issue is not directly related to the middleware.

**Comment by BerkeleyTrue** [comment]
@pouu69 Some investigation turned up the fact that Object.assign is not automatically polyfilled by babel-preset-es2015. This is counterintuitive but nonetheless the source of the bug.

**Comment by BerkeleyTrue** [comment]
I've updated the title to reflect that.
