### ISSUE TITLE
Permanent notifications

### ISSUE THREAD

**Issue by achtan** [pburtchaell/react-notification#88]
Hi, i have some notifications that i don't want to hide (dismiss) unless user clicks on it...
`{dismissAfter:0}` not working

**Comment by pburtchaell** [comment]
@achtan, this is currently not a feature. However, if you would like to make a PR, I'd be happy to implement it.

**Comment by pburtchaell** [comment]
There was some work done for this in PR #67.

**Comment by pburtchaell** [comment]
This is released in `react-notification@6.2.0`.

**Comment by achtan** [comment]
`{dismissAfter:false}` not working, notification will autohide after 2s

**Comment by leshek-pawlak** [comment]
I've fixed it. https://github.com/pburtchaell/react-notification/pull/95

**Comment by BerkeleyTrue** [comment]
@achtan Can you open a separate issue?

**Comment by achtan** [comment]
done
