### ISSUE TITLE
pass Notification to barStyleFactory

### ISSUE THREAD

**Issue by achtan** [pburtchaell/react-notification#89]
my calculation of `bottom` depends on `Notification.key`

**Comment by BerkeleyTrue** [comment]
Hello @achtan 

Can you provide more details of your use case?

**Comment by achtan** [comment]
if I set `Notification.key = 'timer'` then I want to show this notification on left top corner, but if `Notification.key` is any other value than should by shown in left bottom corner

**Comment by BerkeleyTrue** [comment]
Sounds like you have two different stacks, is that correct?

**Comment by achtan** [comment]
hmm, yes that's true

**Comment by BerkeleyTrue** [comment]
It might be easier to use two StackNotification components. That way each can have their own lifecycles and styles.

**Comment by pburtchaell** [comment]
Yes, you would want to use two notification stack components, @achtan.
